mintty/mintty

src/winmain.c

When running "mintty -p@2" on msys2 under Windows 10 WM_DPICHANGED (and win_adapt_term_size(false,*true*)) happens before term structure was initialized with proper sizes.

rupor-github

---

src/winmain.c

This fixes, at least for me, the scaling of titlebars when using multiple monitors with different DPI.
Everything works as expected, except for context menus which are still too big on the lower-DPI monitor.
One strange issue is that Windows sends a `WM_SIZE` message *during* the call to `EnableNonClientDpiScaling`. At this time, the window is not fully constructed (`WM_CREATE` has not been sent yet), but `win_adapt_term_size` tries to call `GetClientRect`, gets invalid data, and the program crashes. The `resizing = true;`, `resizing = false` code makes mintty ignore `WM_SIZE` during this phase.
Screenshot showing mintty before and after, on my regular-DPI external monitor (the laptop's screen is high-DPI):

Fix per-monitor scaling of titlebars

---

src/base64.c
src/base64.h
src/config.c
src/config.h
src/term.c
src/term.h
src/termout.c
src/win.h
src/winmain.c

Hi mintty experts,
See discussion in #258.
The feature is disabled by default. Nedd set 'AllowSetSelection' to true in .minttyrc to enable it.
Works with UTF-8 and non UTF-8 terminal.
Some limitation:
1. Read from clipborad is not supported.
2. No more than 1536 can be copy into clipboard. (Limits by length of cmd_buf)
3. Always use system clipboard.

term: Add osc52 clipboard support.

---

lang/ja.po

I created Japanese translations of mintty.
However, I found some issues when I translated.
* The width of the option dialogbox is not enough to show the translated messages.
I needed to increase the width. E.g.:
```diff
--- a/src/res.rc
+++ b/src/res.rc
@@ -6,7 +6,7 @@
IDI_MAINICON ICON "../icon/terminal.ico"
-IDD_MAINBOX DIALOGEX DISCARDABLE 32, 8, 256, DIALOG_HEIGHT
+IDD_MAINBOX DIALOGEX DISCARDABLE 32, 8, 310, DIALOG_HEIGHT
STYLE DS_SHELLFONT | DS_MODALFRAME | WS_POPUP | WS_CAPTION | WS_SYSMENU
CAPTION DIALOG_TITLE
FONT 8, DIALOG_FONT
```
* Help messages (`--help`) and error messages for command line options are not translated.
It seems that `finish_config()` should be called before using `_()`. E.g.:
```diff
--- a/src/winmain.c
+++ b/src/winmain.c
@@ -2283,8 +2283,10 @@ main(int argc, …
```

Add Japanese translations

---

src/winmain.c

fixed the bug when using sessions switcher, the minimum window can not restore to normal size

fix restore wrong win HWND

---

src/term.c
src/term.h
src/termline.c
src/termout.c
src/win.h
src/winclip.c
src/wintext.c

(let me know if you want to split this PR)
Initially I only wanted to improve the bold font/colour/shadow control. I did
end up doing that, and these are the last two commits.
This is how BoldAsFont and BoldAsColour affect ANSI/default colours:
```
AsFont  AsColour  Previously                Now
------  --------  ------------------------  --------------------------------
no      yes       both only colour          both only colour (same, default)
yes     no        both only thick           both only thick (same)
yes     yes       both thick, ANSI +colour  both thick+colour (new)
no      no        both only thick           both thick, ANSI +colour (xterm)
Two combinations are the same, xterm-like moved from yes/yes to no/no,
and we now have an additional behaviour where both are …
```

Improve bold configuration, improve dim behavior

---

src/termclip.c
src/wintext.c

Just a minor bugfix, and unrelated renamed variable for clarity.

fix copy-to-rtf with invisible true-colour

---

docs/mintty.1
src/wintext.c

Note: this PR demonstrates the bold config improvements, while knowingly ignoring the behavior of dim, copying to rtf, combined characters, custom selection colours, and visual bell background-highlight style. PR #710 does the same as this PR while taking those into account.
Terminology:
- Bold Font: font variant thicker than the normal font. Sometimes we don't have it or can't use it.
- "Shadow" (same as "overstrike"): emulate bold font using a normal font (redraw with 1px offets to render it thicker). Typically inferior to bold font, but has the advantage that we can always use it.
- "Thick": use bold font if possible, and if not possible then use shadow.
Colour classes:
- "ANSI": the normal 8 ansi colours (0-7).
- "Default": default terminal foreground colour. Not part of the ANSI …

Pr bold demonstration

---

src/winmain.c

In reference to #729; the window style chosen with `-B frame` allows no movement at all. The `Alt+Click` functionality works regardless of border style.
The code works by telling the desktop that the client area is actually the title bar.
If necessary I can work on adding the modifier to the options dialog. Where should it go? For Windows, any keys besides `Alt` may prove problematic due to unconfigurable UI behavior. `Shift` is also popular.

Add Ctrl+Alt+Click window movement.

---

src/config.h
src/winmain.c
src/winpriv.h

This change adds basic support for per-window DPI awareness v2, introduced with Windows 10 1703.
In the long run, this enables mintty to use WM_GETDPISCALEDSIZE to resize the window pixel-perfectly when the pixel density changes so that the terminal's size in rows×cols stays constant.
For the moment, the basic support gets rid of mintty's window flipping back and forth between different screens A↔B if I drag it from a screen A onto a screen B with a different pixel density.

Add basic support for per-window DPI awareness v2, remove window flutter

---

src/config.c
src/wininput.c
src/winmain.c
src/wintext.c

It was reported to the oss-security mailing list in
https://seclists.org/oss-sec/2018/q4/82 that GCC 7 and 8 have known
issues generating code for nested functions, essentially voiding any
Data Execution Protection (DEP).
As it is unclear how quickly GCC can be fixed, let's just avoid the
nested functions altogether.
See https://github.com/git-for-windows/git/issues/1725 for the discussion on the Git for Windows issue tracker that triggered my working on this PR.
Note: this patch mainly moves the nested functions out of their previous
host function, if necessary adds a suffix to the function name, and in
several cases declares structures to be passed via the `lParam` argument
of the `Enum*()` functions, to retain access to the local variables of
the former host function.
Note, too, that …

Avoid nested functions

---

themes/dracula

Upstream change: https://github.com/dracula/mintty/commit/fb841f316f43e8aaccc8a08c1e7a4e037206654e
Upstream change comment:
> Change BoldBlack Color to Avoid Overlap by Background Color
This for example fixes unreadable text in htop.
I noticed this issue when I used git-bash (https://github.com/git-for-windows/git/issues/2135). Git people suggested to contact upstream. Here I am.

Update dracula theme from upstream

---

docs/mintty.1
docs/mintty.1.html
src/config.c
src/config.h
src/winmain.c

Rapid consecutive bells in mintty can cause a harsh buzzing sound.
The effect is present whether using system sounds, a WAV file, or `BellFreq`/`BellLen`.  You can observe it (well, hear it) with this shell command that produces many bells:  `printf "\a%.0s" {1..100}`  
This short patch adds a config directive, `BellInterval`, which dictates the minimum time, in milliseconds, between bells.  Bells triggered during the post-bell silence period are ignored.
NB: bells are played asynchronously, so this interval includes the duration of the bell itself.  In other words, if the bell sound is itself longer than `BellInterval`, you'll get the old behavior with no guaranteed silence.

BellInterval directive: quash bells for this many msec after the last

---

src/termout.c

[Tera Term](https://ttssh2.osdn.jp/index.html.en) supports some IME control sequences: TTIMERS, TTIMESV and TTIMEST.
See: https://ttssh2.osdn.jp/manual/en/about/ctrlseq.html
This introduces the same functions to mintty.

Support IME control sequences

---

src/wintext.c

Current processing of `OSC 112` only reset the cursor colour indexed by
`CURSOR_COLOUR_I`, but drawing code of cursor will use colour indexed by
`IME_CURSOR_COLOUR_I` when IME is opened.

Fix Bug #903 That `OSC 112` Don't Work When IME Is Opened

---

docs/mintty.1
src/wininput.c

Corresponding code for issue (#923).
Function names are changed to dashes and added `switch-visible-next/prev`.

added switch(-visible)-next/prev KeyFunctions for switching virtual tabs

---

src/winmain.c

Fixes #983 
* Use undocumented api `RtlGetNtVersionNumbers` to get build number.
* Determine if it is 1903+, and use different apis.
Before (current one shipped with msys2):
After:

Enhanced dark mode.

---

src/child.c
src/winmain.c

The window opened with `alt+f2` preserves window size, but not the window placement.
Pressing `alt+f2` on a maximized window opens a window with the size of a maximized window, but the opened window is not maximized, which looks strange.

maximize child windows if the parent window is maximized.

---

src/child.h
src/winmain.c

When tabbar is enabled, users may expect that all mintty windows are
placed at the same position.
If Alt+F2 is used, the new window is placed at the same position as the
current window. However, if mintty is executed in another way, the
position is not the same as the current window.
This fixes the position of a new window even if Alt+F2 is not used.

tabbar: Fix startup position

---

src/wintab.c

The height calculation in win_toggle_tabbar() was wrong. So, when the
function was called, the tabbar was recreated every time.
Because of this, changing the title sometimes took very long time.
(With the default installation of Cygwin, the current directory is shown
as the title. Thus, on my slow machine, executing a `cd` command
sometimes took more than one second.)
Fix the height calculation and remove an unused variable.

tabbar: Don't recreate the tabbar every time

---

src/child.c
src/winmain.c

This fixes two issues:
1. Distinguish a maximised window from a fullscreen window.
This is an additional fix to #1044.
2. Fix Alt+Shift+F2 behavior on a maximised window.
When Alt+Shift+F2 was pressed on a maximised window, the new window didn't become a maximised window.

tabbar: Fix startup position of maximised window

---

src/child.c
src/termout.c
src/winmain.c
src/wintab.c
src/wintab.h

This fixes two issues about window positioning.
1. Fix Alt+F2 behaviour when the window is maximised.
See: https://github.com/mintty/mintty/pull/1045#issuecomment-709704486
This also changes the behaviour of `CSI 9 ; [0-3] t`.
1. Maximise the window vertically.
`echo -e '\e[9;2t'`
2. Maximise the window.
`echo -e '\e[9;1t'`
3. Restore the window.
`echo -e '\e[9;0t'`
This didn't restore the original window size before maximised vertically.
But now the original size is restored.
(I'm not sure about the behaviour in other terminals, though.)
2. Consider the size of tabbar on startup.
Close #1046.

Fix window positioning

---

src/winmain.c

Without this change, the focus might go to an unrelated window when closing a mintty window.
This makes tabbar more like actual tabbed UI.

tabbar: Bring next window to top when closing

---

LICENSE
docs/mintty.1
docs/readme-msys.html
docs/readme.html
src/appinfo.h
src/config.c
src/config.h
src/term.h
src/termout.c
src/wintext.c
themes/helmholtz
themes/kohlrausch
wiki/CtrlSeqs.md

Add the ability to specify separate foreground and background values for
the 16 ANSI colours, so that e.g. blue text can be bright enough to be
readable on a dark background, while background blue can be dark enough
to not interfere with light foreground text, e.g. in Midnight Commander.
The values can be given as semicolon-separated pairs in config files.
When only one value is present, it is used for both the foreground and
background, to ensure backward capability with existing themes.
Also add mintty-specific control sequence OSC 7765 for setting and
querying the foreground and background variants of the ANSI colour
values. This sequence does not touch the first sixteen xterm256 colours
that can be controlled through the OSC 4 and 104 sequences. Conversely,
though, for backward …

Separate foreground and background values for ANSI colours

---

src/termclip.c
src/winclip.c

The ability to open Windows filenames through Ctrl+click or the Open menu command got lost when removal of backslash quotes for to-be-opened filenames was added in win_open to support opening filenames with escaped spaces and special characters in them.
Restore Windows filename support by only treating backslashes before characters that are special to Unix shells as quotes. (Many of those are illegal in Windows filenames anyway.)
Assume that paths starting with a double backslash are Windows UNC paths.
The ability to open paths with spaces had actually itself got lost because code in term_open truncated the path at the first non-leading space, so remove that.
Also avoid casting away const in win_open, and tweak some comments.

Restore ability to open Windows paths

---

src/term.c
src/term.h
src/termmouse.c
src/termout.c
wiki/CtrlSeqs.md

Proposing the following three main changes to mousewheel handling. Further details in the individual commit messages.
Don't convert line scrolling events to page scrolling events when they exceed the terminal height. This was my idea to start with, but in hindsight I don't think it was a good one because we don't actually know how many lines correspond to a page as far as the application is concerned, or whether it supports page up/down events in the first place. I think this simplifies the code a bit, and helps witht the following changes.
If the Alt key is pressed, modify mousewheel events sent as cursor/page up/down keycodes or as mintty's application wheel codes accordingly.  (Ctrl and Shift are already used for other purposes.)
When enabled, this sends Alt-modified cursor up/down …

Alt-modified mousewheel mode and other wheel tweaks

---

docs/mintty.1
src/wininput.c

A lone Alt key press in Windows applications normally brings up the application menu bar (which is why its virtual keycode is VK_MENU). There's no such menu bar in mintty, which relies on the context menu and window menu instead, so make lone Alt key presses available for mapping in the KeyFunctions setting.
The action is triggered when the Alt key is released, but only if no other modifier was down when the Alt key was pressed, and if nothing else was pressed in-between.
Also make sure that AltGr does not trigger this action or Alt code processing, unless the AltGrIsAlsoAlt setting is enabled.
One use case for this is to map Alt to the context menu via the 'menu-text' action, to make it easier to reach on keyboards that don't have the context menu key.
Another is to map it to ^[, i.e. …

Support lone Alt key presses in KeyFunctions

---

src/config.c

There are more than 256 config options (!), which means that using a uchar is no longer sufficient for storing the index of options found in the config file or changed in the UI.
The overflow meant that for example a BoldBlue setting in the config file (which currently has option index 262) turned into a TekForegroundColour setting (with index 6) when changing some unrelated setting in the config dialog and saving.

Fix option index overflow in remember_file_options

---

src/termout.c

The characters listed here (e.g. "「" (U+300C)) don't follow the FontChoice option:
https://github.com/mintty/mintty/blob/78c7d205d586ed87c946b00dc62034ea54c96e7b/src/termout.c#L5224-L5225
Consider the following settings:
```
Font=Anonymous Pro  # ASCII font
FontChoice=CJK:1
Font1=IPAGothic     # Japanese font
```
U+300C is a double width CJK character so `win_char_width()` should return 2 here:
https://github.com/mintty/mintty/blob/78c7d205d586ed87c946b00dc62034ea54c96e7b/src/termout.c#L5222-L5231
However, FONTFAM is not set to `term.curs.attr.attr` at this point, then `win_char_width()` returns 1 and the `TATTR_EXPAND` flag is unintentionally set.  As the result, U+300C is not shown correctly. (The left half of the glyph of U+300C is expanded.)
FONTFAM should be set before calling …

Some CJK characters don't follow the FontChoice option

---

themes/tender

I have added the tender theme, which is based off of [tender.vim](https://github.com/jacoborus/tender.vim). 
- tender.vim, pull requests [#63](https://github.com/jacoborus/tender.vim/pull/63) & [#64](https://github.com/jacoborus/tender.vim/pull/64)
- Kitty-themes, pull request [#125](https://github.com/kovidgoyal/kitty-themes/pull/125)
>Note: I am using Starship, Dejavu Sans Mono 10pt

add: tender theme

---

src/winmain.c

When opening a new tab, it is shown at the left-most tab, and after a while, it is moved to the right-most part since
fa1f16bc772b049872ef2a1ada85dbfd0f1dc898.
Initialise the timestamp earlier so a new tab is shown at the right-most part.

Initialise the timestamp earlier

---

src/wintab.c

The old implementation didn't correctly detect the end of dragging if
the left mouse button was released out of the tab bar.  Sometimes, tabs
were highlighted unintentionally. Or even crashes occurred.
* Use SetCapture()/ReleaseCapture() to detect the end of dragging.
* Change the mouse cursor while dragging.
* Change the tab order in real-time.

Improve tab reordering

---

src/wintab.c

Set the focus to the main window after tab reordering is finished.
Users couldn't type texts or commands after tab reordering without clicking the main window.

Restore focus after tab reordering
